# Site settings
title: Winslet Event Designs
email: andrewcod749@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Premier Cake designs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: andrewcod749
github_username:  andrew749

# Build settings
markdown: kramdown
